### PR TITLE
Refactored components (except App.js) into container/presentation com…

### LINKED ISSUE #10: Refactor PostAnEvent component into Container/Presentation
PostAnEventContainer renders PostAnEvent and passes in a handler that saves the data.

PostAnEvent will render the form and call the handler passing in its state in onSubmit().

### PR DESCRIPTION
**Pull request by mgregory22**
…ponents

Resolves #10, #11,#15

The Edit Event buttons on each event are just temporary to demonstrate editability.

### CODE REVIEW

**Review by shmup — COMMENTED** [review]
How do you feel about Foo.js and FooContainer.js and Bar.js and BarContainer.js being in the same directory? The naming convention is clear enough to not need the extra separation with different directories.

At a minimum I don't know if I like the shortened name "cont" and "pres". Thoughts?

**Comment by mgregory22** [comment]
Yeah, I didn't really know what to name them.  I was just following this article: https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0

**Comment by shmup** [comment]
I suppose we can refactor later but I kinda wanna see all the components with their accompanying containers side by side. The current file naming you're doing is good. If you disagree we can just merge this and deal with the idea later. :)

**Comment by mgregory22** [comment]
Well, I'll put them in the same directory then and call it something you like.

**Comment by shmup** [comment]
Let's try your thing out for now. Just call it containers and... presenters? views? Heh, up to you.

**Comment by mgregory22** [comment]
They're very similar to controllers and views, aren't they?

**Review by shmup — APPROVED** [review]

**Pull request merged**
